<a href="https://colab.research.google.com/github/Hadi02-gif/Amazon_Sales_Analysis/blob/main/Visualizing_Business_KPIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This cell imports necessary libraries (`pandas`, `matplotlib.pyplot`, `seaborn`, `plotly.express`), loads the `amazon_sales_dataset.csv` file into a pandas DataFrame named `df`, and then displays the first 5 rows of the DataFrame to give an initial overview of the data.

In [6]:
# Analyze customer distribution by country
country_counts = df['country'].value_counts().reset_index()
country_counts.columns = ['country', 'customer_count']

# Display the top countries by customer count
display(country_counts.head())

# Plot Customer Distribution by Country using Plotly
fig = px.bar(
    country_counts.nlargest(10, 'customer_count'), # Display top 10 countries
    x='customer_count',
    y='country',
    orientation='h',
    title='Customer Distribution by Country',
    labels={'customer_count': 'Number of Customers', 'country': 'Country'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

  country  customer_count
0   India           10000

This cell displays a concise summary of the DataFrame `df` using `df.info()`. This output is crucial for understanding the data types of each column, identifying the number of non-null values, and checking the memory usage, which helps in initial data quality assessment.

In [7]:
# Reset the index to ensure 'order_date' is a column if it was previously set as index
df.reset_index(inplace=True, drop=False)

# Convert 'order_date' to datetime objects
df['order_date'] = pd.to_datetime(df['order_date'])

# Set 'order_date' as the index for time-series operations
df.set_index('order_date', inplace=True)

# Resample the data to get monthly total sales (revenue)
monthly_revenue = df['total_sales'].resample('ME').sum().reset_index()
monthly_revenue.columns = ['order_date', 'total_revenue']

# Display the first few rows of the monthly revenue data
display(monthly_revenue.head())

# Plot Revenue over time using Plotly
fig = px.line(
    monthly_revenue,
    x='order_date',
    y='total_revenue',
    title='Revenue Over Time'
)
fig.update_layout(xaxis_title='Date', yaxis_title='Total Revenue')
fig.show()

  order_date  total_revenue
0 2026-01-31   4.899901e+08
1 2026-02-28   1.521390e+08

This cell calculates the monthly revenue over time. It first ensures the 'order_date' column is in datetime format and sets it as the DataFrame's index. Then, it resamples the 'total_sales' data monthly ('ME' for month-end) and sums the sales to get `monthly_revenue`. Finally, it displays the first few rows of this data and generates a line plot using Plotly Express to visualize the revenue trend over time.

In [4]:
# Calculate total sales for each product
product_sales = df.groupby('product_name')['total_sales'].sum().nlargest(10).reset_index()
product_sales.columns = ['product_name', 'total_sales']

# Display the top 10 products by sales
display(product_sales)

# Plot Top 10 Products by Sales using Plotly
fig = px.bar(
    product_sales,
    x='total_sales',
    y='product_name',
    orientation='h',
    title='Top 10 Products by Total Sales',
    labels={'total_sales': 'Total Sales', 'product_name': 'Product Name'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

  product_name   total_sales
0     maintain  2.096518e+06
1      include  1.930786e+06
2      trouble  1.711159e+06
3       suffer  1.629241e+06
4         will  1.590366e+06
5        trade  1.539003e+06
6          big  1.470008e+06
7          cut  1.466105e+06
8         many  1.450177e+06
9        level  1.404670e+06

This cell identifies the top 10 products by total sales. It groups the DataFrame by `product_name`, sums the `total_sales` for each, and then selects the top 10. The results are displayed, and a horizontal bar chart is generated using Plotly Express to visually represent these top-performing products.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load the dataset
df = pd.read_csv('/content/sample_data/amazon_sales_dataset.csv')

# Display the first 5 rows of the DataFrame
display(df.head())

,order_id,order_date,ship_date,delivery_date,order_status,customer_id,customer_name,country,state,city,...,product_name,category,sub_category,brand,quantity,unit_price,discount,shipping_cost,total_sales,payment_method
0,A10000,2026-01-31,2026-01-31,2026-01-08,Delivered,C5691,Ricky Potter,India,South Carolina,New Joe,...,without,Home,Furniture,Doyle-Jordan,3,42467.79,0.26,60.85,94339.3438,Card
1,A10001,2026-01-20,2026-02-03,2026-02-03,Delivered,C9811,Chris Davenport,India,Tennessee,Madisonmouth,...,school,Home,Furniture,Davis LLC,2,36138.76,0.24,112.96,55043.8752,COD
2,A10002,2026-01-15,2026-02-07,2026-01-03,Delivered,C7341,Timothy Gallagher,India,Iowa,East Larryberg,...,I,Electronics,Laptop,Watson and Sons,4,47148.93,0.14,64.11,162256.4292,UPI
3,A10003,2026-01-18,2026-01-15,2026-01-20,Delivered,C4012,Angela Collins,India,Kentucky,South Margaretshire,...,step,Electronics,Laptop,"Sandoval, Buckley and Solis",1,18487.99,0.06,114.15,17492.8606,Card
4,A10004,2026-01-27,2026-01-04,2026-01-23,Delivered,C1328,David Davidson DDS,India,North Dakota,Velasquezview,...,bit,Home,Kitchen,"Key, Bautista and Bowen",1,1742.25,0.10,40.47,1608.4950,UPI

This cell analyzes the customer distribution by country. It counts the occurrences of each country in the 'country' column, displays the top countries by customer count, and then generates a horizontal bar chart using Plotly Express to visualize the distribution across the top 10 countries.

In [2]:
# Display basic information about the DataFrame to check data types and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10000 non-null  object
 1   order_date      10000 non-null  object
 2   ship_date       10000 non-null  object
 3   delivery_date   10000 non-null  object
 4   order_status    10000 non-null  object
 5   customer_id     10000 non-null  object
 6   customer_name   10000 non-null  object
 7   country         10000 non-null  object
 8   state           10000 non-null  object
 9   city            10000 non-null  object
 10  product_id      10000 non-null  object
 11  product_name    10000 non-null  object
 12  category        10000 non-null  object
 13  sub_category    10000 non-null  object
 14  brand           10000 non-null  object
 15  quantity        10000 non-null  int64
 16  unit_price      10000 non-null  float64
 17  discount        10000 non-null  float64
 18  shipping_cost   10000 non-null  float64
 19  total_sales     10000 non-null  float64
 20  payment_method  10000 non-null  object
dtypes: float64(4), int64(1), object(16)
memory usage: 1.6+ MB

This cell analyzes the customer distribution by state. It counts the occurrences of each state in the 'state' column, displays the top states by customer count, and then generates a horizontal bar chart using Plotly Express to visualize the distribution across the top 10 states.

In [8]:
# Analyze customer distribution by state
state_counts = df['state'].value_counts().reset_index()
state_counts.columns = ['state', 'customer_count']

# Display the top states by customer count
display(state_counts.head())

# Plot Customer Distribution by State using Plotly
fig = px.bar(
    state_counts.nlargest(10, 'customer_count'), # Display top 10 states
    x='customer_count',
    y='state',
    orientation='h',
    title='Customer Distribution by State',
    labels={'customer_count': 'Number of Customers', 'state': 'State'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

            state  customer_count
0         Arizona             238
1        Delaware             225
2  North Carolina             224
3     Connecticut             219
4        Arkansas             213

This cell analyzes total sales for each product category. It groups the DataFrame by 'category', sums the 'total_sales' for each, and then selects the top 10 categories. The results are displayed, and a horizontal bar chart is generated using Plotly Express to visualize these top-performing categories.

In [9]:
# Calculate total sales for each category
category_sales = df.groupby('category')['total_sales'].sum().nlargest(10).reset_index()
category_sales.columns = ['category', 'total_sales']

# Display the top 10 categories by sales
display(category_sales)

# Plot Top 10 Categories by Sales using Plotly
fig = px.bar(
    category_sales,
    x='total_sales',
    y='category',
    orientation='h',
    title='Top 10 Categories by Total Sales',
    labels={'total_sales': 'Total Sales', 'category': 'Product Category'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

      category   total_sales
0  Electronics  2.193563e+08
1         Home  2.147638e+08
2      Fashion  2.080091e+08

This cell analyzes the total sales for each payment method. It groups the DataFrame by 'payment_method', sums the 'total_sales' for each, and then displays the results. A horizontal bar chart is generated using Plotly Express to visually represent the total sales attributed to each payment method.

In [11]:
# Calculate total shipping costs for each payment method
shipping_cost_by_payment = df.groupby('payment_method')['shipping_cost'].sum().reset_index()
shipping_cost_by_payment.columns = ['payment_method', 'total_shipping_cost']

# Display the shipping costs by payment method
display(shipping_cost_by_payment)

# Plot Shipping Costs by Payment Method using Plotly
fig = px.bar(
    shipping_cost_by_payment,
    x='total_shipping_cost',
    y='payment_method',
    orientation='h',
    title='Total Shipping Costs by Payment Method',
    labels={'total_shipping_cost': 'Total Shipping Cost', 'payment_method': 'Payment Method'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

  payment_method  total_shipping_cost
0            COD            216320.85
1           Card            212985.43
2     NetBanking            213943.48
3            UPI            207282.16

This cell analyzes the total shipping costs for each payment method. It groups the DataFrame by 'payment_method', sums the 'shipping_cost' for each, and then displays the results. A horizontal bar chart is generated using Plotly Express to visually compare the shipping costs across different payment methods.

In [10]:
# Calculate total sales for each payment method
payment_method_sales = df.groupby('payment_method')['total_sales'].sum().reset_index()
payment_method_sales.columns = ['payment_method', 'total_sales']

# Display the sales by payment method
display(payment_method_sales)

# Plot Sales by Payment Method using Plotly
fig = px.bar(
    payment_method_sales,
    x='total_sales',
    y='payment_method',
    orientation='h',
    title='Total Sales by Payment Method',
    labels={'total_sales': 'Total Sales', 'payment_method': 'Payment Method'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

  payment_method   total_sales
0            COD  1.637298e+08
1           Card  1.612822e+08
2     NetBanking  1.582953e+08
3            UPI  1.588218e+08

This cell explores the relationship between `discount` and `total_sales` using a scatter plot. It uses Plotly Express to visualize individual data points, where each point represents a transaction's discount percentage and total sales. Hovering over points reveals `product_name` and `category`.

In [12]:
# Explore the relationship between discount and total sales
fig = px.scatter(
    df,
    x='discount',
    y='total_sales',
    title='Relationship Between Discount and Total Sales',
    labels={'discount': 'Discount (%)', 'total_sales': 'Total Sales'},
    hover_data=['product_name', 'category'] # Add additional data to hover tooltip
)
fig.update_layout(xaxis_title='Discount (%)', yaxis_title='Total Sales')
fig.show()

This cell calculates the average order value for each payment method. It groups the DataFrame by 'payment_method', calculates the mean of 'total_sales' for each, and then displays the results. A horizontal bar chart is generated using Plotly Express to visually compare the average order values across different payment methods.

In [13]:
# Calculate the average order value for each payment method
avg_order_value_by_payment = df.groupby('payment_method')['total_sales'].mean().reset_index()
avg_order_value_by_payment.columns = ['payment_method', 'average_order_value']

# Display the average order value by payment method
display(avg_order_value_by_payment)

# Plot Average Order Value by Payment Method using Plotly
fig = px.bar(
    avg_order_value_by_payment,
    x='average_order_value',
    y='payment_method',
    orientation='h',
    title='Average Order Value by Payment Method',
    labels={'average_order_value': 'Average Order Value', 'payment_method': 'Payment Method'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

  payment_method  average_order_value
0            COD         64435.180981
1           Card         63874.127836
2     NetBanking         63572.422995
3            UPI         64984.371782

This cell compares total shipping costs across different product categories. It groups the DataFrame by 'category', sums the 'shipping_cost' for each, and then displays the results. A horizontal bar chart is generated using Plotly Express to visually represent the total shipping costs per category.

In [14]:
# Calculate total shipping costs for each category
category_shipping_costs = df.groupby('category')['shipping_cost'].sum().reset_index()
category_shipping_costs.columns = ['category', 'total_shipping_cost']

# Display the shipping costs by category
display(category_shipping_costs)

# Plot Shipping Costs by Category using Plotly
fig = px.bar(
    category_shipping_costs,
    x='total_shipping_cost',
    y='category',
    orientation='h',
    title='Total Shipping Costs by Category',
    labels={'total_shipping_cost': 'Total Shipping Cost', 'category': 'Category'}
)
fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

      category  total_shipping_cost
0  Electronics            282101.44
1      Fashion            280827.01
2         Home            287603.47